language: generic
dist: bionic
install:
- source ./texlive/texlive_install.sh
cache:
  directories:
  - "/tmp/texlive"
  - "$HOME/.texlive"
before_script: cd $TRAVIS_BUILD_DIR
script:
- texliveonfly tmp.tex
- latexmk -pdf tmp.tex
deploy:
  provider: releases
  api_key:
    secure: rkVcMEysQI+WDkOQyzcHVJvi7pNHavskVOSvtoX0q1MSu+AR36IWScB7gG6U0pBQxwHUr3VRzRGbKA4CvzFG459J04db/5/TWloy834fF48Vj09FrA75+oneybkNPKLT13qa/Wrpy/p/Il9/Lp/w8LvJuFEXSj5p37qyzHXgMrrjocKigwGLDbJSGsjX+n3wOmpXq+NHD6PnBAzCgLx+ViMSvD95fnn6439jv6WKPePGuaQhg7tsJhZ4488HeMVuCFdIkrAZXaS0PtrqdQxErw4AyMjhlXfnE9w+ty+GtcWe7eS55KpXzkqWsPbA5cIzuxA8QMv4L/Gjbz3gemQXAb782sP/jPFTZEhGyf7MXcwNosw1WKPFxadgqzaYpyR0qIn4ezEjpS5c548yUXCrHTLkU1RKxnxYlGpgeFHWOPZZpHcz5q5/SBnhJehHesIlR4p5Vva66nFB7OqDkH1FzLHmA1ySIYsy8hmZNELLdu+EOCTbe70iCqlko+gjje6vReVSHgJwVXbuuAuhKr850lQrzNHj8xcEqo4FRhiJVtHmXaJCyfWmKdlpXhVUugVPEKlMl2FsI64fSi9qgBtqnpv0995f9Q6VouqW2WSTABFhAEnQa9bbpJ8wddpnZ8nzU8x/HZ/VtCHb8Klht2xyhoERyr3WlB6x2VAgnykG3wg=
  file: 
  - "./tmp.pdf"
  skip_cleanup: true
  on:
    repo: tylee-fdcl/git_travis_pdflatex
    tags: true
    branch: master
